directory: /mnt/omv/Music
library: /mnt/omv/.beets/musiclibrary.db
import:
    move: no
    copy: yes
    hardlink: no
plugins: inline fetchart web mbsync
paths:
    default: '$albumartist/$album%if{$albumdisambig, ($albumdisambig)}/$artist - $album - $track - $title'
    multidisc: '$albumartist/$album%if{$albumdisambig, ($albumdisambig)}/$artist - $album - $disc-$track - $title'
item_fields:
    multidisc: 1 if disctotal > 1 else 0
fetchart:
    cautious: yes
